# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/smartisan/osborn/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/smartisan/osborn

PRODUCT_COPY_FILES += \
    vendor/smartisan/osborn/proprietary/vendor/lib64/hw/fingerprint.goodix.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.goodix.so \
    vendor/smartisan/osborn/proprietary/vendor/lib64/libgf_ca.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_ca.so \
    vendor/smartisan/osborn/proprietary/vendor/lib64/libgf_hal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_hal.so \
    vendor/smartisan/osborn/proprietary/vendor/lib64/libgoodixfingerprintd_binder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgoodixfingerprintd_binder.so
